version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: docker:17.05.0-ce
    steps:
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Dependencies
          command: apk add --no-cache curl git jq make openssh
      - run:
          name: Artifactory Login
          command: docker login -u ${ARTIFACTORY_USERNAME} -p ${ARTIFACTORY_PASSWORD} -e engineering+circleci@upside.com upsidetravel-docker.jfrog.io
      - checkout
      - run:
          name: Build container
          command: make image
      - run:
          name: Tests
          command: make runtests
      - deploy:
          command: |
            if [[ `echo $CIRCLE_BRANCH | grep -E "^(master|hotfix)$"` ]]; then 
              make push
            fi
            if [[ `echo $CIRCLE_BRANCH | grep -E "^(master)$"` ]]; then 
              make deploy
            fi
